### ISSUE TITLE
Strange printing of --help

### ISSUE THREAD

**Issue by langston-barrett** [gallais/agdARGS#3]
When I use `--help` on my binary, the following gets printed:
```
agda-schemeScheme, in Agda!
  eval       Evaluate a line
  repl       Read-eval-print loop
  --help     Display this help
  --parse-onlyParse but don't execute
  --version  Output version information and exit
  -h         Display this help%  
```
There seem to be three issues:
 1. There is no newline after the binary name
 2. The width of the option column doesn't scale with the length of the option names
 3. There is no newline at the end

Thanks for the awesome library, I'll try and look into these!

**Comment by gallais** [comment]
I guess I should generate [a Table](https://github.com/gallais/agdARGS/blob/4d7f08eca60fde5d34abc772b0f52e08ba7413f1/agdARGS/Data/Table.agda#L42) and then displaying it would be super simple!
